name: C/C++ CI

on:
  push:
    branches: [ CI ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: configure
      run: |
        sudo apt-get install libvulkan-dev
        cmake vulkan-kompute/ -Bvulkan-kompute/build/ \
                  -DKOMPUTE_OPT_BUILD_TESTS=1                \
                  -DKOMPUTE_OPT_INSTALL=1                    \
                  -DKOMPUTE_OPT_ENABLE_SPDLOG=1              \
                  -DSPDLOG_INSTALL=1                         \
                  -DKOMPUTE_OPT_REPO_SUBMODULE_BUILD=1
#        mkdir build 
#        cd build
#        cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: | 
        make -C vulkan-kompute/build/ -j
        make -C vulkan-kompute/build/ install
#        cmake --build build
    #- name: test
    #  run: cd build && ctest

#  build-windows:
#
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [windows-latest, windows-2016]
#    
#    steps:
#    - uses: actions/checkout@v1
#    - name: configure
#      run: mkdir build && cd build && cmake ..
#    - name: build
#      run: cmake --build build --config Debug
#    - name: test
#      run: cd build && ctest
